  
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/fr/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "main"
    ignore:
      - dependency-name: "org.eclipse.persistence:*"
        update-types: ["version-update:semver-major"] # ignore new major versions of eclipse dependencies for now
  
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "v3-main"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "v3-main"
