<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.insee.eno</groupId>
        <artifactId>eno</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>eno-ws</artifactId>
    <name>Eno web-service app</name>

    <properties>
        <springDoc.version>3.1.1</springDoc.version>

        <!-- !!! Version properties overridden from Spring Boot !!! -->
        <tomcat.version>11.0.25</tomcat.version>
    </properties>

    <dependencies>
        <!-- Spring boot web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <!-- Eno modules -->
        <dependency>
            <groupId>fr.insee.eno</groupId>
            <artifactId>eno-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.insee.eno</groupId>
            <artifactId>eno-treatments</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Models -->
        <dependency>
            <groupId>fr.insee.pogues</groupId>
            <artifactId>pogues-model</artifactId>
            <version>${poguesModel.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.insee.lunatic</groupId>
            <artifactId>lunatic-model</artifactId>
            <version>${lunaticModel.version}</version>
        </dependency>

        <!-- Web client -->
        <!-- since Spring MVC RestTemplate class is deprecated, the webflux dependency is added to import WebClient -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webclient</artifactId>
        </dependency>


        <!-- Spring doc (swagger) -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springDoc.version}</version>
        </dependency>

        <!-- Testing -->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webclient-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
