name: Build docker

on: workflow_dispatch

env:
  ENOBRANCH: v3-develop
  LUNATICBRANCH: dev-pairwise
  POGUESBRANCH: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout Lunatic model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ env.LUNATICBRANCH }}
          repository: InseeFr/Lunatic-model
          path: Lunatic-model

      - name: Build with Maven Lunatic model
        working-directory: ./Lunatic-model
        run: mvn install -Djar.finalName="lunatic-model" -B -V --file pom.xml

      - name: Checkout Pogues model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ env.POGUESBRANCH }}
          repository: InseeFr/Pogues-model
          path: Pogues-model

      - name: Build with Maven Pogues model
        working-directory: ./Pogues-model
        run: mvn install -Djar.finalName="pogues-model" -B -V --file pom.xml

      - name: Checkout Eno repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ env.ENOBRANCH }}
          repository: InseeFr/Eno
          path: Eno

      - name: Build with Gradle Eno
        working-directory: ./Eno/eno-core
        run: gradle publishToMavenLocal

      - name: Test, package and analyze with gradle & SonarCloud
        run: gradle test # mvn verify sonar:sonar -Dsonar.projectKey=InseeFr_Eno-WS -Dsonar.organization=inseefr -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout Lunatic model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ env.LUNATICBRANCH }}
          repository: InseeFr/Lunatic-model
          path: Lunatic-model

      - name: Build with Maven Lunatic model
        working-directory: ./Lunatic-model
        run: mvn install -Djar.finalName="lunatic-model" -B -V --file pom.xml

      - name: Checkout Pogues model repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ env.POGUESBRANCH }}
          repository: InseeFr/Pogues-model
          path: Pogues-model

      - name: Build with Maven Pogues model
        working-directory: ./Pogues-model
        run:
          mvn install -Djar.finalName="pogues-model" -B -V --file pom.xml

      - name: Checkout Eno repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ env.ENOBRANCH }}
          repository: InseeFr/Eno
          path: Eno

      - name: Build with Gradle Eno-WS
        working-directory: ./Eno/eno-ws
        run: gradle build

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: build/libs/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: inseefr/eno-ws
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          default_branch: 535-v3-ci-docker
          tags: "3.0.0-SNAPSHOT"
