name: Eno V3 test

on:
  pull_request:
    branches:
      - 'v3-develop'
    types: [opened, synchronize, reopened]
    paths-ignore: ['docs/**', 'logo/**', 'Dockerfile', 'README**.md']

jobs:
  test:
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'deploy-snapshot') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: You shall not pass!
        run: ./gradlew test
